### ISSUE TITLE
`redirectTo` is not working

### ISSUE THREAD

**Issue by renardeinside** [supabase/auth-ui#76] opened 2022-11-22 22:26 UTC
# Bug report

## Describe the bug

I'm trying to setup an auth with Supabase and supabase auth. Unfortunately the `redirectTo` argument seems either ignored or works not as expected.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create a new app with nextjs + react + supabase-auth-ui-react. 
2. use the following code

```js
import { Auth, ThemeSupa } from '@supabase/auth-ui-react';

export default function JoinPage() {
    const session = useSession()
    const supabase = useSupabaseClient()
    
    <Auth
                    supabaseClient={supabase}
                    providers={["github"]}
                    theme="evenDarker"
                    redirectTo='/me'
                />
}
```

3. go to browser and try to auth with any method. 

With email, it remains the same. 
With github, it adds a # to the end of the URL, but none of this makes a proper redirect. 

## Expected behavior

Redirect happens.

## System information

- OS: [e.g. macOS, Windows] macOS
- Browser (if applies) [e.g. chrome, safari] chrome
- Version of supabase-js: [e.g. 6.0.2]:
```
        "@supabase/auth-helpers-nextjs": "^0.5.2",
        "@supabase/auth-helpers-react": "^0.3.1",
        "@supabase/auth-ui-react": "^0.2.6",
        "@supabase/supabase-js": "^2.1.0",
```
- Version of Node.js: [e.g. 10.10.0]:
```
> node -v                                                                                                                                             
v18.12.1
```

**Comment by BeardedBry** [comment] 2022-11-25 17:05
I've noticed the same issue.
After logging in, I need to refresh the page for the redirect to work.

**Comment by BeardedBry** [comment] 2022-11-25 17:08
I'm having the same issue

**Comment by 0x111** [comment] 2022-11-28 20:22
Possible duplicate of https://github.com/supabase/auth-ui/issues/72

**Comment by Gautam-Arora24** [comment] 2022-12-03 08:25
I would like to work on this issue, can anyone assign it to me?

**Comment by Boluwatife2904** [comment] 2022-12-15 11:00
Hey @renardeinside I think the redirectTo expects the full URL to redirect to which should include the Site URL in your supabase dashboard. So for example, if your site url on supabase is 'http://localhost:5173', your redirectTo should be something like 'http://localhost:5173/me' for it to work. 

If your redirectTo prop is a different domain like 'http://localhost:3000/me', it would redirect to the Site URL which you setup on your supabase dashboard.

**Closed** 2023-02-28 23:59 UTC
Labels: bug
